/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-azure/apis/azure/v1beta1"
	v1beta1dbformysql "github.com/upbound/provider-azure/apis/dbformysql/v1beta1"
	v1beta1dbforpostgresql "github.com/upbound/provider-azure/apis/dbforpostgresql/v1beta1"
	v1beta1keyvault "github.com/upbound/provider-azure/apis/keyvault/v1beta1"
	v1beta1network "github.com/upbound/provider-azure/apis/network/v1beta1"
	v1beta1storage "github.com/upbound/provider-azure/apis/storage/v1beta1"
	v1alpha1 "github.com/upbound/provider-azure/apis/v1alpha1"
	v1beta1apis "github.com/upbound/provider-azure/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1dbformysql.SchemeBuilder.AddToScheme,
		v1beta1dbforpostgresql.SchemeBuilder.AddToScheme,
		v1beta1keyvault.SchemeBuilder.AddToScheme,
		v1beta1network.SchemeBuilder.AddToScheme,
		v1beta1storage.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1apis.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
