name: Native Provider Version Bump

on:
  workflow_dispatch: {}

jobs:
  open-bump-pr:
    uses: upbound/official-providers-ci/.github/workflows/native-provider-bump.yml@standard-runners
    with:
      provider-source: hashicorp/azurerm
      go-version: 1.19
    secrets:
      TOKEN: ${{ secrets.OFFICIAL_PROVIDERS_GA_TOKEN }}
