name: Updoc

on:
  workflow_dispatch: {}

jobs:
  publish-docs:
    uses: upbound/official-providers-ci/.github/workflows/provider-updoc.yml@standard-runners
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
